[package]
name = "conllx-utils"
version = "0.2.1"
authors = ["Daniël de Kok <me@danieldk.eu>"]

[dependencies]
conllx = "0.3"
itertools = "0.4"
lazy_static = "0.2"
maplit = "0.1"
petgraph = "0.2"
getopts = "0.2"
reservoir = "0.2"
rand = "0.3"
regex = "0.1"
