[package]
name = "conllx-utils"
version = "0.2.0"
authors = ["Daniël de Kok <me@danieldk.eu>"]

[dependencies]
conllx = "0.2.0"
itertools = "0.4.7"
lazy_static = "0.1.15"
maplit = "0.1.3"
petgraph = "0.2.2"
getopts = "0.2.0"
reservoir = "0.2.0"
rand = "0.3.13"
regex = "0.1"
